lukec/stripe-perl

lib/Net/Stripe/Charge.pm, t/live.t
Also add tests for metadata in charge & customer
=> Implement metadata in Charge object

dist.ini
This now matches that displayed on MetaCPAN
=> Update version number

lib/Net/Stripe.pm, t/local.t
1. Don't attempt to instantiate objects which don't have a corresponding class
2. Test that we don't die parsing a REST response containing an unexpected field.
=> fix Problem with get_customer #76

lib/Net/Stripe.pm
This is just a set of minor (and fairly pedantic) documentation changes.
=> Doc fixups

lib/Net/Stripe.pm, t/live.t
see https://github.com/lukec/stripe-perl/issues/78
=> Issue #78 - fix get_cards

lib/Net/Stripe.pm
set user agent string to Net::Stripe/dev when $Net::Stripe::VERSION is unset
=> Set user agent string for dev environment

lib/Net/Stripe/Card.pm, t/live.t
Fix typo for output field address_line1_check
=> Fix typo for output field address_line1_check

lib/Net/Stripe.pm
=> Fix `starting_after` not passed properly

lib/Net/Stripe.pm, lib/Net/Stripe/Charge.pm, t/live.t
added the unit tests that were lacking for #73
=> Charge receipt email

lib/Net/Stripe.pm, t/live.t
extension of #93, adding its companion pagination argument and tests for their usage.
=> add ending_before and tests for pagination arguments

lib/Net/Stripe.pm, t/live.t
should be able to filter customers by email address, per https://stripe.com/docs/api#list_customers-email
=> add email argument to get_customers

README.pod
Attempt to fix POD errors rendered on Github
=> UTF8 Encoding POD

lib/Net/Stripe.pm
any breaking changes, non-backwards-compatible changes or other 'gotchas' should be documented in this section, with additional details in the commit message and code if necessary.
=> add RELEASE NOTES section to POD

README.pod, lib/Net/Stripe.pm, t/live.t
* remove invalid argument types from post_card(), per <https://github.com/lukec/stripe-perl/issues/138>
* remove dead code paths from post_card() and make conditional structure more explicit, per discussion in <https://github.com/lukec/stripe-perl/pull/133>
* add unit tests for all calling forms, per <https://github.com/lukec/stripe-perl/issues/139>
* update the POD
=> cleanup post_card()

README.pod, lib/Net/Stripe.pm, lib/Net/Stripe/Token.pm, t/live.t
* add type attribute and add test
* add client_ip attribute
* fix typo in token retrieval test
* closes <https://github.com/lukec/stripe-perl/issues/170> and <https://github.com/lukec/stripe-perl/issues/174>
=> update Token attributes

t/live.t
* closes <https://github.com/lukec/stripe-perl/issues/169>
=> remove duplicate post_charge() tests

README.pod, lib/Net/Stripe.pm, lib/Net/Stripe/Plan.pm, t/live.t
* clean up and augment unit tests
* update POD
* closes <https://github.com/lukec/stripe-perl/issues/70>
=> add metadata for Plan

lib/Net/Stripe/Coupon.pm, t/live.t
* clean up and augment unit tests
* update POD
=> add metadata for Coupon

README.pod, lib/Net/Stripe.pm, lib/Net/Stripe/Charge.pm, lib/Net/Stripe/Customer.pm, lib/Net/Stripe/Resource.pm, lib/Net/Stripe/Source.pm, lib/Net/Stripe/TypeConstraints.pm, t/live.t, t/local.t, weaver.ini
* add Source object, methods and unit tests
* add backward-compatible source attributes and parameters for Charge and Customer
* update unit tests to pass 'source' instead of 'card' where the calling form is not germane to the test
* update POD
=> Add source to charge and customer

README.pod, lib/Net/Stripe.pm, lib/Net/Stripe/List.pm, t/local.t
* allow for retrieval of all objects of a given type without local pagination code
* add unit tests for related utility methods
=> add _get_all()

README.pod, lib/Net/Stripe.pm, lib/Net/Stripe/Plan.pm, lib/Net/Stripe/Product.pm, lib/Net/Stripe/Resource.pm, lib/Net/Stripe/TypeConstraints.pm, t/live.t, t/local.t, weaver.ini
* add Product object, methods and unit tests
* update Plan object and tests to be compatible post 2018-02-05 <https://stripe.com/docs/upgrades#2018-02-05>
* update POD
=> add Product

README.pod, lib/Net/Stripe.pm, lib/Net/Stripe/PaymentIntent.pm, lib/Net/Stripe/PaymentMethod.pm, lib/Net/Stripe/Resource.pm, lib/Net/Stripe/TypeConstraints.pm, t/live.t, weaver.ini
* added PaymentMethod object, methods and unit tests
* added PaymentIntent object, methods and unit tests
* updated POD
* closes <https://github.com/lukec/stripe-perl/issues/115>
=> add PaymentMethod and PaymentIntent

lib/Net/Stripe.pm, t/live.t
* pass customer id in get_invoiceitems()
* add failing unit tests
* closes <https://github.com/lukec/stripe-perl/issues/187>
=> get_invoiceitems() not passing customer id
