dist.ini
There are two minor failures on the CPANTS kwalitee page for this module.  The two commits in this PR fix these issues.  It was merely necessary to define the minimum Perl version and to automatically generate the `provides` section in `META.yml`.
=> Fix kwalitee fails

lib/Net/Stripe/Resource.pm
An ABSTRACT statement was missing in `Net::Stripe::Resource` this change adds the relevant line.  I've adapted the text from other ABSTRACTs within the project, so hopefully the text is correct for the given file.
=> Add missing ABSTRACT

.gitignore
This stops the automatically generated .build directory (created via dzil)
from appearing in `git status`.
=> Ignore dzil-generated .build directory

dist.ini
This is because ContributorsFromGit isn't as well maintained and ETHER
created Git::Contributors out of frustration to fix this issue (see
https://github.com/RsrchBoy/Dist-Zilla-Plugin-ContributorsFromGit/issues/19).
This has the same functionality and builds and tests properly and should be
considered a better alternative.
This PR is provided in the hope that it helps.  Comments and/or questions welcome!
=> Replace ContributorsFromGit with Git::Contributors

lib/Net/Stripe.pm, lib/Net/Stripe/BalanceTransaction.pm, lib/Net/Stripe/Coupon.pm, lib/Net/Stripe/List.pm, t/live.t
This change contains no functional changes; it is purely cosmetic. However, sometimes people like to have trailing whitespace purged from their code, hence this PR. If the change in this PR is not wished for, then it can be closed without being merged.
=> Remove trailing whitespace

lib/Net/Stripe/Charge.pm, t/live.t
Charge objects from Stripe have a "invoice" property which can hold an Invoice ID. The invoice ID is populated if the charge was created from an invoice, which includes any charges made as a result of subscription.
=> Implement "invoice" property on Charge objects.

dist.ini
The major change in this PR is that the implicit dependencies within `weaver.ini` are installed as part of the `dzil authordeps --missing | cpanm` installation step.
=> Update dist ini

t/live.t
instead of manually constructing paths and calling _get() directly, use the more-robust get_card()
=> replace _get() with get_card in unit tests

lib/Net/Stripe/Card.pm, lib/Net/Stripe/Coupon.pm, lib/Net/Stripe/Discount.pm
it appears that there are a few instances of 'use Moose::Util::TypeConstraints' where the code in the module is not making use of it. but i clearly could be overlooking something.
=> remove extraneous use Moose::Util::TypeConstraints

lib/Net/Stripe/Plan.pm
trivial update for the sake of consistency. could also remove the qw() in Net::Stripe::BalanceTransaction.
=> use consistent syntax for use Moose::Util::TypeConstraints

lib/Net/Stripe/Card.pm, t/live.t
in its current form, Net::Stripe::Card does not seem to handle card metadata on post or get.
=> add metadata field for Net::Stripe::Card

lib/Net/Stripe/Card.pm, t/live.t
in its current form, Net::Stripe::Card does not seem to handle address_city on post or get.
=> add address_city field for Net::Stripe::Card

lib/Net/Stripe.pm, t/live.t
you seem to be able to post a new customer with an existing token, but it doesn't seem possible to add a new card to an existing customer by passing a token object or token id from a card that has already been tokenized, by Stripe.js, for example.
=> allow addition of new card to customer via passing of an existing token

README.pod, dist.ini, lib/Net/Stripe.pm, weaver.ini
update POD, dist.ini and weaver.ini:
* add encoding declaration to POD to fix unsafe character warning. this was fixed directly in README.pod during a previous commit, but was overwritten during the dzil regeneration of README.pod.
* add missing section for Discount methods in weaver.ini
* remove trailing period from copyright_holder in dist.ini. apparently dzil adds a period when regenerating README.pod.
* regenerate README.pod
=> fix POD oversights

lib/Net/Stripe.pm, lib/Net/Stripe/Charge.pm, lib/Net/Stripe/Plan.pm, t/live.t
update statement_description to backwards-compatible statement_descriptor for Net::Stripe::Charge and Net::Stripe::Plan <https://stripe.com/docs/upgrades#2014-12-17>;
add failing test to detect previously-missing attribute in Net::Stripe::Charge;
my testing, and the [documentation](https://stripe.com/docs/upgrades#2014-12-17
) shows this change to be backwards-compatible:
"If not on this API version or newer, providing a statement_descriptor still triggers the statement_description behavior."
we were previously passing statement_description to `Net::Stripe::Charge`, but it was being dropped on the floor since there was no matching attribute.
=> update statement_description to statement_descriptor

lib/Net/Stripe.pm
based on the unit tests we currently have in place, these changes allow the code to work with all API versions all the way back to the first documented API version. to be clear, i am sure that this is not strictly necessary, and that nobody is using these versions in the wild. but it turned out to be an easy fix, and it provides a nice starting point for the first version-specific release.
the code should be pretty self-explanatory, but it basically takes Stripes list formats from before they used a hashref with a arrayref of data, and coerces it into a format that `Net::Stripe::List` can digest.
the only bit i have any qualms about is the url generation. i am pretty confident about the format, but i don't have any way to test the kinds of code paths that would make use of these returned …
=> make Net::Stripe compatible with API back to 2011-06-21

t/live.t
The tests on `$no_amount` became redundant when the Token tests were
reworked in `8ca8bcc` to remove `amount` and `currency`, and should
have been removed at that time. Closes <https://github.com/lukec/stripe-perl/issues/126>.
=> remove redundant Token tests

lib/Net/Stripe.pm
* only called in post_customer() for hashref argument to _post()
* _post() calls convert_to_form_fields() for hashrefs
* convert_to_form_fields() skips hashref keys with undefined values
* closes <https://github.com/lukec/stripe-perl/issues/136>
=> _defined_arguments() is unnecessary

lib/Net/Stripe.pm, lib/Net/Stripe/Card.pm, t/live.t
i left this stalled a while ago, but i figured i'd dust it off for inclusion in the next release. discussed preciously in #100 .
=> allow updates to existing cards

README.pod, lib/Net/Stripe.pm, lib/Net/Stripe/Customer.pm, lib/Net/Stripe/Resource.pm, t/live.t
* updated Kavorka signature to remove non-functional or illegitimate argument types
* removed Net::Stripe::Card and disallowed card id for card, as neither form is valid conceptually <https://github.com/lukec/stripe-perl/issues/138>
* always create a Net::Stripe::Customer object before _post() to take advantage of argument coercion during objectification <https://github.com/lukec/stripe-perl/issues/148>
* include omitted arguments in object creation
* clean up and centralize Net::Stripe:Token coercion code, since we always need the token id
* added unit tests to exercise all allowed argument forms for customer creation and customer update <https://github.com/lukec/stripe-perl/issues/139>
* closes <https://github.com/lukec/stripe-perl/issues/138>
=> fix post_customer() arguments

README.pod, lib/Net/Stripe.pm, t/live.t
* check for either of the valid succesful values, 'paid' for Stripe API versions before 2015-02-18 or 'succeeded' for versions after <https://stripe.com/docs/upgrades#2015-02-18>
=> update unit tests for Charge->status

README.pod, lib/Net/Stripe.pm, t/live.t
* Stripe strongly discourages direct handling of PANs (primary account numbers), even in test mode
* accounts created after October 2017 return an invalid_request_error when passing PANs
* removed the methods and parameter constraints that allow direct handling of PANs and their associated unit tests
* updated the unit tests to use test tokens instead of card numbers
=> deprecate direct handling of PANs

lib/Net/Stripe.pm
* fix oversight from `5ad870c`
* this conditional is not needed since `card` no longer accepts HashRef
* closes <https://github.com/lukec/stripe-perl/issues/163>
=> remove card hash handling code in post_card()

README.pod, lib/Net/Stripe.pm, lib/Net/Stripe/Charge.pm, t/live.t
* update capture_charge() to allow for partial capture
* add refunds attribute to charge object
* add unit tests for partial capture
* closes https://github.com/lukec/stripe-perl/issues/144
=> capture partial charge

t/live.t
* pass the test token directly where there is no further introspection of $token
* remove cases where introspection of $token is not germane to the current unit test
* leave cases where we are expressly testing passing of a token object or where $token is needed for other reasons
* closes <https://github.com/lukec/stripe-perl/issues/172>
=> remove unnecessary token object creation

README.pod, lib/Net/Stripe.pm, lib/Net/Stripe/Customer.pm, t/live.t
* add default_card to form_fields()
* update attribute to 'rw'
* update unit tests
* update POD
* closes <https://github.com/lukec/stripe-perl/issues/158>
=> default_card not updating in post_customer()

README.pod, lib/Net/Stripe.pm, lib/Net/Stripe/TypeConstraints.pm, t/live.t, t/local.t
* update convert_to_form_fields() to handle objects
* use convert_to_form_fields() for processing passed data and URI for encoding, elminating _get_collections() and _get_with_args()
* remove manual serialization in _delete()
* add unit tests for code path to be deprecated later
* closes <https://github.com/lukec/stripe-perl/issues/167>
=> remove manual serialization in _get_collections() and _get_with_args()

README.pod, lib/Net/Stripe.pm, lib/Net/Stripe/Customer.pm, t/live.t, t/local.t
* add backwards-compatible 'balance' attribute for Customer objects
* add 'balance' argument for post_customer()
* add unit tests
* update POD
* addresses API update 2019-10-17 <https://stripe.com/docs/upgrades#2019-10-17>
=> add balance for Customer

lib/Net/Stripe/Invoice.pm, t/live.t
* re-add customer attribute accidentally removed during 30a702b
* update unit tests to detect this regression
* closes <https://github.com/lukec/stripe-perl/issues/196>
=> re-add customer to Invoice

t/live.t
* certain tests appear to now be failing because of changes in the API response from the Stripe side
* 'amount' is not allowed for reusable sources. Stripe updated API response for ach_credit_transfer.
* metadata (re)setting behavior for PaymentMethod is now consistent with other object types
* the Stripe API now returns quotes around values in some error strings
* address update behavior for sources has been updated to be similar to that of payment_methods
* closes <https://github.com/lukec/stripe-perl/issues/207>
=> fix failing tests
